TITLE = "Tunnel Evacuation Simulation"

# Screen size
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Simulation speed
FPS = 10

# Grid
DRAW_GRID = False
TILE_SIZE = 20
GRID_WIDTH = SCREEN_WIDTH / TILE_SIZE
GRID_HEIGHT = SCREEN_HEIGHT / TILE_SIZE

# Colors
BG = (234, 219, 198)
GRID_COLOR = (192, 137, 91)
AGENT_COLOR = (89, 99, 172)
WALL_COLOR = (0, 0, 255)
EXIT_COLOR = (0, 255, 0)

# Images
BACKGROUND_IMG = "assets/road-lane.png"
AGENT_IMG = "assets/agent.png"

# Simulation Parameters
NUM_OF_AGENTS = 30

# Walls
WALL_WIDTH = SCREEN_WIDTH
WALL_HEIGHT = 10
# positions:
WALL_1_X = 0
WALL_1_Y = 75
WALL_2_X = 0
WALL_2_Y = SCREEN_HEIGHT - 85

# Exits
EXIT_WIDTH = GRID_WIDTH
EXIT_HEIGHT = WALL_HEIGHT
# positions:
EXIT_1_X = SCREEN_WIDTH / 2
EXIT_1_Y = WALL_1_Y
EXIT_2_X = SCREEN_WIDTH / 2
EXIT_2_Y = WALL_2_Y


